//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystemProgramShell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSurname { get; set; }
        public string CustomerMiddleName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public bool VIP { get; set; }
        public bool Gender { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public bool CustomerIDType { get; set; }
        public string CustomerIDNo { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string PreferedLang { get; set; }
        public System.DateTime DateInSystem { get; set; }
    
        public virtual GuestCard GuestCard { get; set; }
    }
}
