//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystemProgramShell
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestCard
    {
        public GuestCard()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int GuestCardNo { get; set; }
        public string TravelAgency { get; set; }
        public System.DateTime CheckInDateTime { get; set; }
        public System.DateTime CheckOutDateTime { get; set; }
        public short RoomNo { get; set; }
        public string SpecialRequirements { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual HouseKeeping HouseKeeping { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
