//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystemProgramShell
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseKeeping
    {
        public HouseKeeping()
        {
            this.GuestCard = new HashSet<GuestCard>();
        }
    
        public short RoomNo { get; set; }
        public string RoomStatus { get; set; }
        public Nullable<System.DateTime> StopSaleBegin { get; set; }
        public Nullable<System.DateTime> StopSaleEnd { get; set; }
        public string StopSaleNote { get; set; }
    
        public virtual ICollection<GuestCard> GuestCard { get; set; }
    }
}
