//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystemProgramShell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentsCard { get; set; }
        public decimal RoomPrice { get; set; }
        public Nullable<decimal> DiscountCash { get; set; }
        public Nullable<byte> DiscountPercens { get; set; }
        public Nullable<decimal> Paid { get; set; }
    
        public virtual GuestCard GuestCard { get; set; }
    }
}
